import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const fonts = Poppins({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body         className={`${fonts.className} m-0 text-base antialiased pt-4 font-normal dark:bg-slate-900 leading-default bg-gray-50 text-slate-500"`}
>{children}</body>
    </html>
  );
}
